//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cordon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cordon.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid age..
        /// </summary>
        internal static string AgeValidator_ValidationError {
            get {
                return ResourceManager.GetString("AgeValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be at least 18 years old..
        /// </summary>
        internal static string AgeValidator_ValidationError_IsAdultOnly {
            get {
                return ResourceManager.GetString("AgeValidator_ValidationError_IsAdultOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field does not equal any of the values specified in AllowedValuesValidator..
        /// </summary>
        internal static string AllowedValuesValidator_ValidationError {
            get {
                return ResourceManager.GetString("AllowedValuesValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid bank card number..
        /// </summary>
        internal static string BankCardValidator_ValidationError {
            get {
                return ResourceManager.GetString("BankCardValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid Base64 encoding..
        /// </summary>
        internal static string Base64StringValidator_ValidationError {
            get {
                return ResourceManager.GetString("Base64StringValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid Chinese name..
        /// </summary>
        internal static string ChineseNameValidator_ValidationError {
            get {
                return ResourceManager.GetString("ChineseNameValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} contains invalid Chinese characters..
        /// </summary>
        internal static string ChineseValidator_ValidationError {
            get {
                return ResourceManager.GetString("ChineseValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid color value..
        /// </summary>
        internal static string ColorValueValidator_ValidationError {
            get {
                return ResourceManager.GetString("ColorValueValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        internal static string CompareValidator_ValidationError {
            get {
                return ResourceManager.GetString("CompareValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a valid date..
        /// </summary>
        internal static string DateOnlyValidator_ValidationError {
            get {
                return ResourceManager.GetString("DateOnlyValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a valid date in the following format(s): {1}..
        /// </summary>
        internal static string DateOnlyValidator_ValidationError_Formats {
            get {
                return ResourceManager.GetString("DateOnlyValidator_ValidationError_Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a valid datetime..
        /// </summary>
        internal static string DateTimeValidator_ValidationError {
            get {
                return ResourceManager.GetString("DateTimeValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a valid datetime in the following format(s): {1}..
        /// </summary>
        internal static string DateTimeValidator_ValidationError_Formats {
            get {
                return ResourceManager.GetString("DateTimeValidator_ValidationError_Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must not have more than &apos;{1}&apos; decimal places..
        /// </summary>
        internal static string DecimalPlacesValidator_ValidationError {
            get {
                return ResourceManager.GetString("DecimalPlacesValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field equals one of the values specified in DeniedValuesValidator..
        /// </summary>
        internal static string DeniedValuesValidator_ValidationError {
            get {
                return ResourceManager.GetString("DeniedValuesValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid domain name..
        /// </summary>
        internal static string DomainValidator_ValidationError {
            get {
                return ResourceManager.GetString("DomainValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        internal static string EmailAddressValidator_ValidationError {
            get {
                return ResourceManager.GetString("EmailAddressValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be empty..
        /// </summary>
        internal static string EmptyValidator_ValidationError {
            get {
                return ResourceManager.GetString("EmptyValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not end with the string &apos;{1}&apos;..
        /// </summary>
        internal static string EndsWithValidator_ValidationError {
            get {
                return ResourceManager.GetString("EndsWithValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a defined value of enum {1}..
        /// </summary>
        internal static string EnumValidator_ValidationError {
            get {
                return ResourceManager.GetString("EnumValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a valid combination of values defined in enum {1}..
        /// </summary>
        internal static string EnumValidator_ValidationError_SupportFlags {
            get {
                return ResourceManager.GetString("EnumValidator_ValidationError_SupportFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be equal to &apos;{1}&apos;..
        /// </summary>
        internal static string EqualToValidator_ValidationError {
            get {
                return ResourceManager.GetString("EqualToValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field only accepts files with the following extensions: {1}..
        /// </summary>
        internal static string FileExtensionsValidator_ValidationError {
            get {
                return ResourceManager.GetString("FileExtensionsValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string GreaterThanOrEqualToValidator_ValidationError {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string GreaterThanValidator_ValidationError {
            get {
                return ResourceManager.GetString("GreaterThanValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or collection type with a length of exactly &apos;{1}&apos;..
        /// </summary>
        internal static string HaveLengthValidator_ValidationError {
            get {
                return ResourceManager.GetString("HaveLengthValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be empty or have a length of exactly &apos;{1}&apos;..
        /// </summary>
        internal static string HaveLengthValidator_ValidationError_AllowEmpty {
            get {
                return ResourceManager.GetString("HaveLengthValidator_ValidationError_AllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid Id card number format..
        /// </summary>
        internal static string IDCardValidator_ValidationError {
            get {
                return ResourceManager.GetString("IDCardValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid IPv4 address..
        /// </summary>
        internal static string IpAddressValidator_ValidationError {
            get {
                return ResourceManager.GetString("IpAddressValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid IP address (IPv4 or IPv6)..
        /// </summary>
        internal static string IpAddressValidator_ValidationError_AllowIPv6 {
            get {
                return ResourceManager.GetString("IpAddressValidator_ValidationError_AllowIPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be a valid JSON object or array..
        /// </summary>
        internal static string JsonValidator_ValidationError {
            get {
                return ResourceManager.GetString("JsonValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or collection type with a minimum length of &apos;{1}&apos; and maximum length of &apos;{2}&apos;..
        /// </summary>
        internal static string LengthValidator_ValidationError {
            get {
                return ResourceManager.GetString("LengthValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be less than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string LessThanOrEqualToValidator_ValidationError {
            get {
                return ResourceManager.GetString("LessThanOrEqualToValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be less than &apos;{1}&apos;..
        /// </summary>
        internal static string LessThanValidator_ValidationError {
            get {
                return ResourceManager.GetString("LessThanValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a maximum length of &apos;{1}&apos;..
        /// </summary>
        internal static string MaxLengthValidator_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be less than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string MaxValidator_ValidationError {
            get {
                return ResourceManager.GetString("MaxValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid MD5 string..
        /// </summary>
        internal static string MD5StringValidator_ValidationError {
            get {
                return ResourceManager.GetString("MD5StringValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;..
        /// </summary>
        internal static string MinLengthValidator_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string MinValidator_ValidationError {
            get {
                return ResourceManager.GetString("MinValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} cannot be empty or whitespace..
        /// </summary>
        internal static string NotBlankValidator_ValidationError {
            get {
                return ResourceManager.GetString("NotBlankValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not allow empty values..
        /// </summary>
        internal static string NotEmptyValidator_ValidationError {
            get {
                return ResourceManager.GetString("NotEmptyValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} cannot be equal to &apos;{1}&apos;..
        /// </summary>
        internal static string NotEqualToValidator_ValidationError {
            get {
                return ResourceManager.GetString("NotEqualToValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not allow null values..
        /// </summary>
        internal static string NotNullValidator_ValidationError {
            get {
                return ResourceManager.GetString("NotNullValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be null..
        /// </summary>
        internal static string NullValidator_ValidationError {
            get {
                return ResourceManager.GetString("NullValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} has an invalid password format. It must be 8 to 64 characters long and contain at least one letter and one number..
        /// </summary>
        internal static string PasswordValidator_ValidationError {
            get {
                return ResourceManager.GetString("PasswordValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} has an invalid password format. It must be 12 to 64 characters long and contain uppercase letters, lowercase letters, numbers, and special characters..
        /// </summary>
        internal static string PasswordValidator_ValidationError_Strong {
            get {
                return ResourceManager.GetString("PasswordValidator_ValidationError_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid phone number..
        /// </summary>
        internal static string PhoneNumberValidator_ValidationError {
            get {
                return ResourceManager.GetString("PhoneNumberValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid postal code..
        /// </summary>
        internal static string PostalCodeValidator_ValidationError {
            get {
                return ResourceManager.GetString("PostalCodeValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string RangeValidator_ValidationError {
            get {
                return ResourceManager.GetString("RangeValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between &apos;{1}&apos; and &apos;{2}&apos; exclusive..
        /// </summary>
        internal static string RangeValidator_ValidationError_MaxExclusive {
            get {
                return ResourceManager.GetString("RangeValidator_ValidationError_MaxExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between &apos;{1}&apos; exclusive and &apos;{2}&apos;..
        /// </summary>
        internal static string RangeValidator_ValidationError_MinExclusive {
            get {
                return ResourceManager.GetString("RangeValidator_ValidationError_MinExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between &apos;{1}&apos; exclusive and &apos;{2}&apos; exclusive..
        /// </summary>
        internal static string RangeValidator_ValidationError_MinExclusive_MaxExclusive {
            get {
                return ResourceManager.GetString("RangeValidator_ValidationError_MinExclusive_MaxExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must match the regular expression &apos;{1}&apos;..
        /// </summary>
        internal static string RegularExpressionValidator_ValidationError {
            get {
                return ResourceManager.GetString("RegularExpressionValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string RequiredValidator_ValidationError {
            get {
                return ResourceManager.GetString("RequiredValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} only allows a single item..
        /// </summary>
        internal static string SingleValidator_ValidationError {
            get {
                return ResourceManager.GetString("SingleValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not start with the string &apos;{1}&apos;..
        /// </summary>
        internal static string StartsWithValidator_ValidationError {
            get {
                return ResourceManager.GetString("StartsWithValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not contain the string &apos;{1}&apos;..
        /// </summary>
        internal static string StringContainsValidator_ValidationError {
            get {
                return ResourceManager.GetString("StringContainsValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of &apos;{1}&apos;..
        /// </summary>
        internal static string StringLengthValidator_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a minimum length of &apos;{2}&apos; and a maximum length of &apos;{1}&apos;..
        /// </summary>
        internal static string StringLengthValidator_ValidationError_MinimumLength {
            get {
                return ResourceManager.GetString("StringLengthValidator_ValidationError_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must not contain the string &apos;{1}&apos;..
        /// </summary>
        internal static string StringNotContainsValidator_ValidationError {
            get {
                return ResourceManager.GetString("StringNotContainsValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid telephone..
        /// </summary>
        internal static string TelephoneValidator_ValidationError {
            get {
                return ResourceManager.GetString("TelephoneValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a valid time..
        /// </summary>
        internal static string TimeOnlyValidator_ValidationError {
            get {
                return ResourceManager.GetString("TimeOnlyValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a valid time in the following format(s): {1}..
        /// </summary>
        internal static string TimeOnlyValidator_ValidationError_Formats {
            get {
                return ResourceManager.GetString("TimeOnlyValidator_ValidationError_Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid fully-qualified http, https URL..
        /// </summary>
        internal static string UrlValidator_ValidationError {
            get {
                return ResourceManager.GetString("UrlValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid fully-qualified http, https, or ftp URL..
        /// </summary>
        internal static string UrlValidator_ValidationError_SupportsFtp {
            get {
                return ResourceManager.GetString("UrlValidator_ValidationError_SupportsFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid username..
        /// </summary>
        internal static string UserNameValidator_ValidationError {
            get {
                return ResourceManager.GetString("UserNameValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is invalid..
        /// </summary>
        internal static string ValidatorBase_ValidationError {
            get {
                return ResourceManager.GetString("ValidatorBase_ValidationError", resourceCulture);
            }
        }
    }
}
